# ARRAYS

In [4]:
arr1 = ['nagpur',"mumbai",'surat',"kolkata",'bihar',"jaipur",'chennai']

In [5]:
print(type(arr1))

<class 'list'>


In [6]:
arr1[0]

'nagpur'

In [8]:
import numpy
arr2 = numpy.array([10,20,30,40,50])

In [9]:
print(type(arr2))

<class 'numpy.ndarray'>


In [10]:
print(arr2)

[10 20 30 40 50]


In [11]:
arr2

array([10, 20, 30, 40, 50])

In [12]:
arr3=numpy.array((100,200,300,400,500))

In [13]:
type(arr3)

numpy.ndarray

In [14]:
import numpy as np
a0=np.array(10)

In [15]:
print(a0)

10


In [16]:
a0.ndim

0

In [17]:
a0

array(10)

In [18]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10]) # collection of 0th dimension array = 1


In [19]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
a1.ndim

1

In [25]:
a2=np.array([[1,2,3],[10,20,30],[100,200,300],[103,101,102]]) # collection of 1th dimension array= 2


In [26]:
a2

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300],
       [103, 101, 102]])

In [27]:
a2.ndim

2

In [28]:
a3 = np.array([[[1,2,3],[10,11,12],[21,22,23],[31,32,33]]]) # collection of 2 dimension array= 3


In [29]:
a3

array([[[ 1,  2,  3],
        [10, 11, 12],
        [21, 22, 23],
        [31, 32, 33]]])

In [30]:
a3.ndim

3

In [31]:
a4 = np.array([[[[4,44,444,4444]]]])# collection of 3 dimension array= 4

In [32]:
a4

array([[[[   4,   44,  444, 4444]]]])

In [33]:
a4.ndim

4

In [34]:
a4 = np.array([4,44,444,4444], ndmin=4)

In [35]:
a4

array([[[[   4,   44,  444, 4444]]]])

In [36]:
amix1 = np.array(["wardha",1,"nagpur",2])

In [37]:
type(amix1)

numpy.ndarray

In [38]:
amix2 = np.array([True,5])

In [39]:
type(amix2)

numpy.ndarray

In [42]:
amix3 = np.array([False,10])
amix3


array([ 0, 10])

In [41]:
amix2

array([1, 5])

In [43]:
arr1[0]

'nagpur'

In [44]:
arr2[1]

20

In [45]:
a2[1,2]

30

In [46]:
a2[2,2]

300

In [47]:
a3[0,0,0]

1

In [48]:
a3[0,0,1]

2

In [49]:
a3[0,0,2]

3

In [50]:
a3[0,1,0]

10

In [51]:
a4[0,0,0,0]

4

In [52]:
a4[0,0,0,1]

44

In [53]:
a4[0,0,0,2]

444

In [54]:
a4[0,0,0,3]

4444

In [55]:
arrr = np.array([1,2,3,1,2,3,1,2,3])

In [56]:
arrr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [57]:
arr2

array([10, 20, 30, 40, 50])

In [58]:
arr2[-1]

50

In [59]:
arr2[-2]

40

In [60]:
arr2[1:]

array([20, 30, 40, 50])

In [61]:
arr2[:3]

array([10, 20, 30])

In [62]:
arr2[:]

array([10, 20, 30, 40, 50])

In [63]:
x = np.where(arr2 == 50)
print(x)

(array([4], dtype=int64),)


In [67]:
ax = np.where(amix3 == False)
print(ax)

(array([0], dtype=int64),)


In [68]:
x = np.where(arrr == 3)
print(x)

(array([2, 5, 8], dtype=int64),)


In [69]:
sorting = np.array([2,1,5,3,7,5,9,8,5,7,3])

In [70]:
np.sort(sorting)

array([1, 2, 3, 3, 5, 5, 5, 7, 7, 8, 9])

In [71]:
np.insert(arr2,5,60)

array([10, 20, 30, 40, 50, 60])

In [73]:
np.insert(sorting,11,10)

array([ 2,  1,  5,  3,  7,  5,  9,  8,  5,  7,  3, 10])

In [74]:
np.insert(sorting,0,111)

array([111,   2,   1,   5,   3,   7,   5,   9,   8,   5,   7,   3])

In [75]:
np.delete(sorting,0)

array([1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [76]:
sorting

array([2, 1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [77]:
arrr1 = np.insert(arr2,5,60)

In [78]:
arrr1

array([10, 20, 30, 40, 50, 60])

In [79]:
arr2

array([10, 20, 30, 40, 50])

In [80]:
index = [0,1,2]

In [81]:
arrr2 = np.delete(arr2,index)

In [82]:
arrr2

array([40, 50])

In [83]:
arr2

array([10, 20, 30, 40, 50])